// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZHD_Manager;

namespace ZHD_Manager.Migrations
{
    [DbContext(typeof(TrainDatabase))]
    [Migration("20220116160051_Added_CascadeDelete_For_Stations")]
    partial class Added_CascadeDelete_For_Stations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ZHD_Manager.PersonInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PersonList");
                });

            modelBuilder.Entity("ZHD_Manager.PlaceInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WagonInfoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WagonInfoID");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("ZHD_Manager.StationInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ZHD_Manager.TrainInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationOfArrivalID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationOfDepartureID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StationOfArrivalID");

                    b.HasIndex("StationOfDepartureID");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("ZHD_Manager.WagonInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainInfoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("TrainInfoID");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("ZHD_Manager.PlaceInfo", b =>
                {
                    b.HasOne("ZHD_Manager.WagonInfo", null)
                        .WithMany("Places")
                        .HasForeignKey("WagonInfoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZHD_Manager.TrainInfo", b =>
                {
                    b.HasOne("ZHD_Manager.StationInfo", "StationOfArrival")
                        .WithMany("ArrivingTrains")
                        .HasForeignKey("StationOfArrivalID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZHD_Manager.StationInfo", "StationOfDeparture")
                        .WithMany("DepartingTrains")
                        .HasForeignKey("StationOfDepartureID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StationOfArrival");

                    b.Navigation("StationOfDeparture");
                });

            modelBuilder.Entity("ZHD_Manager.WagonInfo", b =>
                {
                    b.HasOne("ZHD_Manager.TrainInfo", null)
                        .WithMany("Wagons")
                        .HasForeignKey("TrainInfoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZHD_Manager.StationInfo", b =>
                {
                    b.Navigation("ArrivingTrains");

                    b.Navigation("DepartingTrains");
                });

            modelBuilder.Entity("ZHD_Manager.TrainInfo", b =>
                {
                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("ZHD_Manager.WagonInfo", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
